#!/usr/bin/env ruby

require 'plist'
require 'optparse'

require './lib/com.apple.airport.preferences.rb'

opt = OptionParser.new
opt.permute!(ARGV)

if (ARGV.length != 2)
  puts "比較対象となるファイルのパス 2 つを引数に指定する必要があります。"
end

file1 = ARGV[0];
file2 = ARGV[1];

plist1 = Plist::parse_xml(file1)
plist2 = Plist::parse_xml(file2)

# TODO: validate these files are readable
# TODO: validate these files are valid plists
# TODO: switch differ by filename or options

split(plist1, plist2)
