#!/usr/bin/env ruby

require 'bundler/setup'

require 'plist'
require 'optparse'

require './lib/monkey_patches/001_add_class_subclass.rb'

opt = OptionParser.new
opt.permute!(ARGV)

if (ARGV.length != 2)
  puts "比較対象となるファイルのパス 2 つを引数に指定する必要があります。"
  exit 1
end

file1 = ARGV[0]
file2 = ARGV[1]

plist1 = Plist::parse_xml(file1)
plist2 = Plist::parse_xml(file2)

# TODO: validate these files are readable
# TODO: validate these files are valid plists

passed = false

Dir['./lib/parser/*.rb'].each { |filepath|
  require filepath
}
ConfigSplitter::BaseParser.subclasses.each{ |class_name|
  obj = class_name.new

  if obj.acceptable?(file1, file2)
    obj.split(plist1, plist2)
    passed = true
    break
  end
}

unless passed
  puts "指定された設定ファイルのパース方法が分かりませんでした。"
  exit 1
end
